jwt:
  secret: ${JWT_SECRET}
baseUrl: ${BASE_URL}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ${S3_REGION}
      auto: false

lol:
  api:
    key: ${RIOT_API}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB #10GB
      max-request-size: 500MB # 10GB
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    # jdbc:mysql://localhost:3306/[TABLE NAME]?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    url: ${DB_URL}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 4
      connection-timeout: 30000 # 30s
      idle-timeout: 600000 # 10분, 유휴 연결의 최대 유지 시간
      max-lifetime: 1800000 # 30분, 연결의 최대 수명


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          apple:
            client-id: ${APPLE_CLIENT_ID} # input apple client id
            redirect-uri: '${baseUrl}/login/oauth2/code/apple'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - openid
              - email
              - name
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys

server:
  tomcat:
    threads:
      max: 150 # 최대 동시 요청수, 기본 200
      min-spare: 20 # 최소한 유지하는 스레드 수, 기본 10
    max-connections: 2000
    #  대기 중인 연결 큐의 최대 크기
    # 대기열이 꽉 차면 추가 요청은 거절됨 (기본값 100)
    accept-count: 2000 # 대기 중인 연결 큐의 최대 크기,
    connection-timeout: 180000 # 3분, 클라이언트 연결 대기 시간

apple:
  clientId: ${APPLE_CLIENT_ID}
  keyId: ${APPLE_KEY_ID}
  teamId: ${APPLE_TEAM_ID}
  privateKey: ${APPLE_PRIVATE_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

logging:
  level:
    root: info
