jwt:
  secret: ${JWT_SECRET}
baseUrl: ${BASE_URL}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ${S3_REGION}
      auto: false

lol:
  api:
    key: ${RIOT_API}

spring:
  profiles:
    include:
      - dev
      - lp
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB #10GB
      max-request-size: 500MB # 10GB
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    # jdbc:mysql://localhost:3306/[TABLE NAME]?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}

  # Dotenv
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          apple:
            client-id: ${APPLE_CLIENT_ID} # input apple client id
            redirect-uri: '${baseUrl}/login/oauth2/code/apple'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - openid
              - email
              - name
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys

apple:
  clientId: ${APPLE_CLIENT_ID}
  keyId: ${APPLE_KEY_ID}
  teamId: ${APPLE_TEAM_ID}
  privateKey: ${APPLE_PRIVATE_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

logging:
  level:
    root: info
