jwt:
  secret: "o-yPEgafIlYXjghL-b0ro3lusiK3DCzjjcNfVYQ91TRTsfgI5Wa1DKz2kbQo1XTzQ-jygK4QO_mThbYR74zsbQ=="

server:
  ssl:
    key-store: keystore.p12
    key-store-password: df159357
    key-store-type: PKCS12

spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    # jdbc:mysql://localhost:3306/[TABLE NAME]?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/gamemuncheol?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: df159357

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 263880571551-lfs15j8esvd0pab984m5dv2rvqvvcgme.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
